version: "0.5"

processes:
  api:
    command: watchexec --restart --watch apps/api --watch crates --exts rs,toml -- cargo run -p api
  web:
    command: watchexec --restart --watch apps/catalog-web --exts ts,tsx,css,html,json -- npm run dev --prefix apps/catalog-web -- --host --port $WEB_PORT
