-- Rename the remaining "catalog" schema names to the product name, Attricat.
ALTER TABLE extension_catalog_batch_intents RENAME TO extension_attricat_batch_intents;
ALTER TABLE workspaces RENAME COLUMN catalog_generation TO attricat_generation;

ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_pkey TO extension_attricat_batch_intents_pkey;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_workspace_id_fkey TO extension_attricat_batch_intents_workspace_id_fkey;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_extension_id_check TO extension_attricat_batch_intents_extension_id_check;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_batch_key_check TO extension_attricat_batch_intents_batch_key_check;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_intent_key_check TO extension_attricat_batch_intents_intent_key_check;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_input_hash_check TO extension_attricat_batch_intents_input_hash_check;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_workspace_id_not_null TO extension_attricat_batch_intents_workspace_id_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_extension_id_not_null TO extension_attricat_batch_intents_extension_id_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_batch_key_not_null TO extension_attricat_batch_intents_batch_key_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_intent_key_not_null TO extension_attricat_batch_intents_intent_key_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_input_hash_not_null TO extension_attricat_batch_intents_input_hash_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_outcome_not_null TO extension_attricat_batch_intents_outcome_not_null;
ALTER TABLE extension_attricat_batch_intents RENAME CONSTRAINT extension_catalog_batch_intents_created_at_not_null TO extension_attricat_batch_intents_created_at_not_null;
ALTER TABLE workspaces RENAME CONSTRAINT workspaces_catalog_generation_check TO workspaces_attricat_generation_check;
ALTER TABLE workspaces RENAME CONSTRAINT workspaces_catalog_generation_not_null TO workspaces_attricat_generation_not_null;
