-- Rename catalog "entities" to "records" across tables, columns, constraints,
-- indexes, permission codes and the stored enumeration values that name them.

-- Enumerated values.
ALTER TABLE blueprints DROP CONSTRAINT blueprints_kind_check;
ALTER TABLE role_grants DROP CONSTRAINT role_grants_scope_type_check;
ALTER TABLE workspace_invitations DROP CONSTRAINT workspace_invitations_scope_type_check;
ALTER TABLE solution_pack_plan_mappings DROP CONSTRAINT solution_pack_plan_mappings_resource_kind_check;
ALTER TABLE solution_pack_plan_actions DROP CONSTRAINT solution_pack_plan_actions_resource_kind_check;
ALTER TABLE solution_pack_application_steps DROP CONSTRAINT solution_pack_application_steps_resource_kind_check;
ALTER TABLE user_notifications DROP CONSTRAINT user_notifications_subject_kind_check;

UPDATE blueprints SET kind = 'record' WHERE kind = 'entity';
UPDATE role_grants SET scope_type = 'record' WHERE scope_type = 'entity';
UPDATE workspace_invitations SET scope_type = 'record' WHERE scope_type = 'entity';
UPDATE solution_pack_plan_mappings SET resource_kind = 'sample_record' WHERE resource_kind = 'sample_entity';
UPDATE solution_pack_plan_actions SET resource_kind = 'sample_record' WHERE resource_kind = 'sample_entity';
UPDATE solution_pack_application_steps SET resource_kind = 'sample_record' WHERE resource_kind = 'sample_entity';
UPDATE user_notifications SET subject_kind = 'record' WHERE subject_kind = 'entity';

ALTER TABLE blueprints ADD CONSTRAINT blueprints_kind_check
    CHECK (kind IS NULL OR kind IN ('record', 'mixin'));
ALTER TABLE role_grants ADD CONSTRAINT role_grants_scope_type_check
    CHECK (scope_type IN ('workspace', 'blueprint_family', 'record', 'context_subtree'));
ALTER TABLE workspace_invitations ADD CONSTRAINT workspace_invitations_scope_type_check
    CHECK (scope_type IN ('workspace', 'blueprint_family', 'record', 'context_subtree'));
ALTER TABLE solution_pack_plan_mappings ADD CONSTRAINT solution_pack_plan_mappings_resource_kind_check
    CHECK (resource_kind IN ('blueprint', 'workspace_setting', 'presentation_asset', 'sample_record', 'prerequisite', 'context', 'publication_channel', 'rule', 'workflow', 'saved_search')) NOT VALID;
ALTER TABLE solution_pack_plan_actions ADD CONSTRAINT solution_pack_plan_actions_resource_kind_check
    CHECK (resource_kind IN ('blueprint', 'workspace_setting', 'presentation_asset', 'sample_record', 'prerequisite', 'context', 'publication_channel', 'rule', 'workflow', 'saved_search')) NOT VALID;
ALTER TABLE solution_pack_application_steps ADD CONSTRAINT solution_pack_application_steps_resource_kind_check
    CHECK (resource_kind IN ('blueprint', 'workspace_setting', 'presentation_asset', 'sample_record', 'prerequisite', 'context', 'publication_channel', 'rule', 'workflow', 'saved_search')) NOT VALID;
ALTER TABLE user_notifications ADD CONSTRAINT user_notifications_subject_kind_check
    CHECK (subject_kind IN ('record', 'agent_conversation'));

-- Permission codes.
INSERT INTO permissions (code, description)
SELECT replace(code, 'entities.', 'records.'), replace(description, 'entities', 'records')
FROM permissions WHERE code LIKE 'entities.%';
UPDATE role_permissions SET permission_code = replace(permission_code, 'entities.', 'records.')
WHERE permission_code LIKE 'entities.%';
UPDATE personal_api_token_permissions SET permission_code = replace(permission_code, 'entities.', 'records.')
WHERE permission_code LIKE 'entities.%';
DELETE FROM permissions WHERE code LIKE 'entities.%';

-- Constraints.
ALTER TABLE attribute_value_history RENAME CONSTRAINT attribute_value_history_entity_id_fkey TO attribute_value_history_record_id_fkey;
ALTER TABLE attribute_value_history RENAME CONSTRAINT attribute_value_history_entity_id_not_null TO attribute_value_history_record_id_not_null;
ALTER TABLE attribute_value_history RENAME CONSTRAINT attribute_value_history_relationship_target_entity_id_fkey TO attribute_value_history_relationship_target_record_id_fkey;
ALTER TABLE attribute_value_history RENAME CONSTRAINT attribute_value_history_workspace_entity_fkey TO attribute_value_history_workspace_record_fkey;
ALTER TABLE attribute_values RENAME CONSTRAINT attribute_values_entity_id_fkey TO attribute_values_record_id_fkey;
ALTER TABLE attribute_values RENAME CONSTRAINT attribute_values_entity_id_not_null TO attribute_values_record_id_not_null;
ALTER TABLE attribute_values RENAME CONSTRAINT attribute_values_relationship_target_entity_id_fkey TO attribute_values_relationship_target_record_id_fkey;
ALTER TABLE attribute_values RENAME CONSTRAINT attribute_values_workspace_entity_fkey TO attribute_values_workspace_record_fkey;
ALTER TABLE attributes RENAME CONSTRAINT attributes_workspace_entity_fkey TO attributes_workspace_record_fkey;
ALTER TABLE audit_event_changes RENAME CONSTRAINT audit_event_changes_entity_id_not_null TO audit_event_changes_record_id_not_null;
ALTER TABLE conversations RENAME CONSTRAINT conversations_context_requires_entity TO conversations_context_requires_record;
ALTER TABLE conversations RENAME CONSTRAINT conversations_entity_id_fkey TO conversations_record_id_fkey;
ALTER TABLE entities RENAME CONSTRAINT entities_blueprint_id_not_null TO records_blueprint_id_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_blueprint_version_fkey TO records_blueprint_version_fkey;
ALTER TABLE entities RENAME CONSTRAINT entities_blueprint_version_not_null TO records_blueprint_version_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_created_at_not_null TO records_created_at_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_id_not_null TO records_id_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_pkey TO records_pkey;
ALTER TABLE entities RENAME CONSTRAINT entities_projections_not_null TO records_projections_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_system_metadata_not_null TO records_system_metadata_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_system_tags_not_null TO records_system_tags_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_updated_at_not_null TO records_updated_at_not_null;
ALTER TABLE entities RENAME CONSTRAINT entities_workspace_blueprint_fkey TO records_workspace_blueprint_fkey;
ALTER TABLE entities RENAME CONSTRAINT entities_workspace_fkey TO records_workspace_fkey;
ALTER TABLE entities RENAME CONSTRAINT entities_workspace_id_not_null TO records_workspace_id_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_approved_at_not_null TO record_approvals_approved_at_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_approved_by_user_id_fkey TO record_approvals_approved_by_user_id_fkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_attribute_code_not_null TO record_approvals_attribute_code_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_check TO record_approvals_check;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_check1 TO record_approvals_check1;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_content_digest_check TO record_approvals_content_digest_check;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_content_digest_not_null TO record_approvals_content_digest_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_context_id_fkey TO record_approvals_context_id_fkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_context_id_not_null TO record_approvals_context_id_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_covered_attributes_not_null TO record_approvals_covered_attributes_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_covers_all_not_null TO record_approvals_covers_all_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_end_reason_check TO record_approvals_end_reason_check;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_ended_by_user_id_fkey TO record_approvals_ended_by_user_id_fkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_entity_id_not_null TO record_approvals_record_id_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_id_not_null TO record_approvals_id_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_pkey TO record_approvals_pkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_status_not_null TO record_approvals_status_not_null;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_workspace_id_entity_id_fkey TO record_approvals_workspace_id_record_id_fkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_workspace_id_fkey TO record_approvals_workspace_id_fkey;
ALTER TABLE entity_approvals RENAME CONSTRAINT entity_approvals_workspace_id_not_null TO record_approvals_workspace_id_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_batch_id_fkey TO record_blueprint_migrations_batch_id_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_blueprint_id_not_null TO record_blueprint_migrations_blueprint_id_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_created_at_not_null TO record_blueprint_migrations_created_at_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_entity_id_fkey TO record_blueprint_migrations_record_id_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_entity_id_not_null TO record_blueprint_migrations_record_id_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_id_not_null TO record_blueprint_migrations_id_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_input_not_null TO record_blueprint_migrations_input_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_issues_not_null TO record_blueprint_migrations_issues_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_pkey TO record_blueprint_migrations_pkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_source_fkey TO record_blueprint_migrations_source_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_source_version_not_null TO record_blueprint_migrations_source_version_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_status_check TO record_blueprint_migrations_status_check;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_status_not_null TO record_blueprint_migrations_status_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_target_fkey TO record_blueprint_migrations_target_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_target_version_not_null TO record_blueprint_migrations_target_version_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_task_owned_not_null TO record_blueprint_migrations_task_owned_not_null;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_workspace_blueprint_source_fkey TO record_blueprint_migrations_workspace_blueprint_source_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_workspace_blueprint_target_fkey TO record_blueprint_migrations_workspace_blueprint_target_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_workspace_entity_fkey TO record_blueprint_migrations_workspace_record_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_workspace_fkey TO record_blueprint_migrations_workspace_fkey;
ALTER TABLE entity_blueprint_migrations RENAME CONSTRAINT entity_blueprint_migrations_workspace_id_not_null TO record_blueprint_migrations_workspace_id_not_null;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_check TO record_channel_publications_check;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_context_id_not_null TO record_channel_publications_context_id_not_null;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_entity_id_not_null TO record_channel_publications_record_id_not_null;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_pkey TO record_channel_publications_pkey;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_published_by_user_id_fkey TO record_channel_publications_published_by_user_id_fkey;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_workspace_id_context_id_fkey TO record_channel_publications_workspace_id_context_id_fkey;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_workspace_id_entity_id_fkey TO record_channel_publications_workspace_id_record_id_fkey;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_workspace_id_fkey TO record_channel_publications_workspace_id_fkey;
ALTER TABLE entity_channel_publications RENAME CONSTRAINT entity_channel_publications_workspace_id_not_null TO record_channel_publications_workspace_id_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_author_user_id_fkey TO record_comments_author_user_id_fkey;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_author_user_id_not_null TO record_comments_author_user_id_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_body_check TO record_comments_body_check;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_body_not_null TO record_comments_body_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_created_at_not_null TO record_comments_created_at_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_entity_id_not_null TO record_comments_record_id_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_id_not_null TO record_comments_id_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_pkey TO record_comments_pkey;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_revision_check TO record_comments_revision_check;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_revision_not_null TO record_comments_revision_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_updated_at_not_null TO record_comments_updated_at_not_null;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_workspace_id_entity_id_fkey TO record_comments_workspace_id_record_id_fkey;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_workspace_id_fkey TO record_comments_workspace_id_fkey;
ALTER TABLE entity_comments RENAME CONSTRAINT entity_comments_workspace_id_not_null TO record_comments_workspace_id_not_null;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revi_workspace_id_extension_id_fkey TO record_extension_annotation_revi_workspace_id_extension_id_fkey;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_entity_id_fkey TO record_extension_annotation_revisions_record_id_fkey;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_entity_id_not_null TO record_extension_annotation_revisions_record_id_not_null;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_extension_id_check TO record_extension_annotation_revisions_extension_id_check;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_extension_id_not_null TO record_extension_annotation_revisions_extension_id_not_null;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_pkey TO record_extension_annotation_revisions_pkey;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_revision_check TO record_extension_annotation_revisions_revision_check;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_revision_not_null TO record_extension_annotation_revisions_revision_not_null;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_updated_at_not_null TO record_extension_annotation_revisions_updated_at_not_null;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_workspace_id_fkey TO record_extension_annotation_revisions_workspace_id_fkey;
ALTER TABLE entity_extension_annotation_revisions RENAME CONSTRAINT entity_extension_annotation_revisions_workspace_id_not_null TO record_extension_annotation_revisions_workspace_id_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_a_reusable_attribute_definit_not_null TO record_reusable_attribute_a_reusable_attribute_definit_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_a_reusable_attribute_revisio_not_null TO record_reusable_attribute_a_reusable_attribute_revisio_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_att_reusable_attribute_definitio_fkey TO record_reusable_attribute_att_reusable_attribute_definitio_fkey;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_att_reusable_attribute_revision__fkey TO record_reusable_attribute_att_reusable_attribute_revision__fkey;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_att_workspace_id_entity_id_reusa_key1 TO record_reusable_attribute_att_workspace_id_record_id_reusa_key1;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_att_workspace_id_entity_id_reusab_key TO record_reusable_attribute_att_workspace_id_record_id_reusab_key;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachmen_workspace_id_entity_id_fkey TO record_reusable_attribute_attachmen_workspace_id_record_id_fkey;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_created_at_not_null TO record_reusable_attribute_attachments_created_at_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_entity_id_not_null TO record_reusable_attribute_attachments_record_id_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_id_not_null TO record_reusable_attribute_attachments_id_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_pkey TO record_reusable_attribute_attachments_pkey;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_position_not_null TO record_reusable_attribute_attachments_position_not_null;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_workspace_id_fkey TO record_reusable_attribute_attachments_workspace_id_fkey;
ALTER TABLE entity_reusable_attribute_attachments RENAME CONSTRAINT entity_reusable_attribute_attachments_workspace_id_not_null TO record_reusable_attribute_attachments_workspace_id_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_actor_user_id_fkey TO record_status_transitions_actor_user_id_fkey;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_attribute_code_not_null TO record_status_transitions_attribute_code_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_check TO record_status_transitions_check;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_context_id_fkey TO record_status_transitions_context_id_fkey;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_context_id_not_null TO record_status_transitions_context_id_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_entity_id_not_null TO record_status_transitions_record_id_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_id_not_null TO record_status_transitions_id_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_kind_check TO record_status_transitions_kind_check;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_kind_not_null TO record_status_transitions_kind_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_occurred_at_not_null TO record_status_transitions_occurred_at_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_pkey TO record_status_transitions_pkey;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_unlocked_not_null TO record_status_transitions_unlocked_not_null;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_workspace_id_entity_id_fkey TO record_status_transitions_workspace_id_record_id_fkey;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_workspace_id_fkey TO record_status_transitions_workspace_id_fkey;
ALTER TABLE entity_status_transitions RENAME CONSTRAINT entity_status_transitions_workspace_id_not_null TO record_status_transitions_workspace_id_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_blueprint_id_not_null TO record_unique_key_values_blueprint_id_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_context_id_not_null TO record_unique_key_values_context_id_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_entity_id_not_null TO record_unique_key_values_record_id_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_code_check TO record_unique_key_values_key_code_check;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_code_not_null TO record_unique_key_values_key_code_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_hash_check TO record_unique_key_values_key_hash_check;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_hash_not_null TO record_unique_key_values_key_hash_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_values_check TO record_unique_key_values_key_values_check;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_key_values_not_null TO record_unique_key_values_key_values_not_null;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_pkey TO record_unique_key_values_pkey;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_value_key TO record_unique_key_values_value_key;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_workspace_id_context_id_fkey TO record_unique_key_values_workspace_id_context_id_fkey;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_workspace_id_entity_id_fkey TO record_unique_key_values_workspace_id_record_id_fkey;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_workspace_id_fkey TO record_unique_key_values_workspace_id_fkey;
ALTER TABLE entity_unique_key_values RENAME CONSTRAINT entity_unique_key_values_workspace_id_not_null TO record_unique_key_values_workspace_id_not_null;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_entity_id_fkey TO extension_operation_run_records_record_id_fkey;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_entity_id_not_null TO extension_operation_run_records_record_id_not_null;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_operation_run_id_entity_id_key TO extension_operation_run_records_operation_run_id_record_id_key;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_operation_run_id_fkey TO extension_operation_run_records_operation_run_id_fkey;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_operation_run_id_not_null TO extension_operation_run_records_operation_run_id_not_null;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_pkey TO extension_operation_run_records_pkey;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_position_check TO extension_operation_run_records_position_check;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_position_not_null TO extension_operation_run_records_position_not_null;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_workspace_id_fkey TO extension_operation_run_records_workspace_id_fkey;
ALTER TABLE extension_operation_run_entities RENAME CONSTRAINT extension_operation_run_entities_workspace_id_not_null TO extension_operation_run_records_workspace_id_not_null;
ALTER TABLE file_retention_holds RENAME CONSTRAINT file_retention_holds_workspace_id_entity_id_fkey TO file_retention_holds_workspace_id_record_id_fkey;
ALTER TABLE publication_channels RENAME CONSTRAINT publication_channels_require_valid_entity_not_null TO publication_channels_require_valid_record_not_null;
ALTER TABLE rule_findings RENAME CONSTRAINT rule_findings_entity_id_fkey TO rule_findings_record_id_fkey;
ALTER TABLE rule_findings RENAME CONSTRAINT rule_findings_entity_id_not_null TO rule_findings_record_id_not_null;
ALTER TABLE rule_findings RENAME CONSTRAINT rule_findings_workspace_id_rule_id_entity_id_context_id_eva_key TO rule_findings_workspace_id_rule_id_record_id_context_id_eva_key;
ALTER TABLE rule_runs RENAME CONSTRAINT rule_runs_scope_entity_id_fkey TO rule_runs_scope_record_id_fkey;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entit_relationship_target_count_check TO solution_pack_plan_sample_recor_relationship_target_count_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entiti_blueprint_logical_key_not_null TO solution_pack_plan_sample_record_blueprint_logical_key_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_blueprint_id_not_null TO solution_pack_plan_sample_records_blueprint_id_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_blueprint_version_check TO solution_pack_plan_sample_records_blueprint_version_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_blueprint_version_not_null TO solution_pack_plan_sample_records_blueprint_version_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_canonical_input_check TO solution_pack_plan_sample_records_canonical_input_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_canonical_input_not_null TO solution_pack_plan_sample_records_canonical_input_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_created_at_not_null TO solution_pack_plan_sample_records_created_at_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_logical_key_check TO solution_pack_plan_sample_records_logical_key_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_logical_key_not_null TO solution_pack_plan_sample_records_logical_key_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_pkey TO solution_pack_plan_sample_records_pkey;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_plan_id_logical_key_key TO solution_pack_plan_sample_records_plan_id_logical_key_key;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_plan_id_not_null TO solution_pack_plan_sample_records_plan_id_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_plan_id_target_id_key TO solution_pack_plan_sample_records_plan_id_target_id_key;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_position_check TO solution_pack_plan_sample_records_position_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_position_not_null TO solution_pack_plan_sample_records_position_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_scalar_count_check TO solution_pack_plan_sample_records_scalar_count_check;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_scalar_count_not_null TO solution_pack_plan_sample_records_scalar_count_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_target_id_not_null TO solution_pack_plan_sample_records_target_id_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_workspace_id_not_null TO solution_pack_plan_sample_records_workspace_id_not_null;
ALTER TABLE solution_pack_plan_sample_entities RENAME CONSTRAINT solution_pack_plan_sample_entities_workspace_id_plan_id_fkey TO solution_pack_plan_sample_records_workspace_id_plan_id_fkey;
ALTER TABLE solution_pack_plans RENAME CONSTRAINT solution_pack_plans_sample_entity_count_not_null TO solution_pack_plans_sample_record_count_not_null;
ALTER TABLE workflow_run_action_targets RENAME CONSTRAINT workflow_run_action_targets_entity_id_fkey TO workflow_run_action_targets_record_id_fkey;
ALTER TABLE workflow_run_action_targets RENAME CONSTRAINT workflow_run_action_targets_entity_id_not_null TO workflow_run_action_targets_record_id_not_null;

-- Foreign keys cloned onto the history partition keep their own names.
ALTER TABLE attribute_value_history_default RENAME CONSTRAINT attribute_value_history_entity_id_fkey TO attribute_value_history_record_id_fkey;
ALTER TABLE attribute_value_history_default RENAME CONSTRAINT attribute_value_history_relationship_target_entity_id_fkey TO attribute_value_history_relationship_target_record_id_fkey;
ALTER TABLE attribute_value_history_default RENAME CONSTRAINT attribute_value_history_workspace_entity_fkey TO attribute_value_history_workspace_record_fkey;

-- Indexes.
ALTER INDEX attribute_value_history_entity_archived_idx RENAME TO attribute_value_history_record_archived_idx;
ALTER INDEX attribute_value_history_default_entity_id_archived_at_id_idx RENAME TO attribute_value_history_default_record_id_archived_at_id_idx;
ALTER INDEX attribute_values_relationship_target_entity_idx RENAME TO attribute_values_relationship_target_record_idx;
ALTER INDEX attributes_workspace_entity_idx RENAME TO attributes_workspace_record_idx;
ALTER INDEX attributes_workspace_entity_reusable_revision_key RENAME TO attributes_workspace_record_reusable_revision_key;
ALTER INDEX audit_event_changes_entity_created_at_idx RENAME TO audit_event_changes_record_created_at_idx;
ALTER INDEX conversations_entity_context_idx RENAME TO conversations_record_context_idx;
ALTER INDEX entities_active_migration_candidates_idx RENAME TO records_active_migration_candidates_idx;
ALTER INDEX entities_blueprint_version_idx RENAME TO records_blueprint_version_idx;
ALTER INDEX entities_projections_gin_idx RENAME TO records_projections_gin_idx;
ALTER INDEX entities_system_tags_idx RENAME TO records_system_tags_idx;
ALTER INDEX entities_workspace_id_key RENAME TO records_workspace_id_key;
ALTER INDEX entity_approvals_active_key RENAME TO record_approvals_active_key;
ALTER INDEX entity_approvals_history_idx RENAME TO record_approvals_history_idx;
ALTER INDEX entity_blueprint_migrations_batch_status_idx RENAME TO record_blueprint_migrations_batch_status_idx;
ALTER INDEX entity_blueprint_migrations_entity_idx RENAME TO record_blueprint_migrations_record_idx;
ALTER INDEX entity_blueprint_migrations_task_batch_entity_key RENAME TO record_blueprint_migrations_task_batch_record_key;
ALTER INDEX entity_channel_publications_published_idx RENAME TO record_channel_publications_published_idx;
ALTER INDEX entity_comments_page_idx RENAME TO record_comments_page_idx;
ALTER INDEX entity_status_transitions_lookup_idx RENAME TO record_status_transitions_lookup_idx;
ALTER INDEX entity_unique_key_values_family_idx RENAME TO record_unique_key_values_family_idx;
ALTER INDEX extension_operation_run_entities_entity_idx RENAME TO extension_operation_run_records_record_idx;
ALTER INDEX file_retention_holds_entity_idx RENAME TO file_retention_holds_record_idx;
ALTER INDEX rule_findings_entity_idx RENAME TO rule_findings_record_idx;

-- Columns.
ALTER TABLE attribute_value_history RENAME COLUMN entity_id TO record_id;
ALTER TABLE attribute_value_history RENAME COLUMN relationship_target_entity_id TO relationship_target_record_id;
ALTER TABLE attribute_values RENAME COLUMN entity_id TO record_id;
ALTER TABLE attribute_values RENAME COLUMN relationship_target_entity_id TO relationship_target_record_id;
ALTER TABLE attributes RENAME COLUMN entity_id TO record_id;
ALTER TABLE audit_event_changes RENAME COLUMN entity_id TO record_id;
ALTER TABLE blueprints RENAME COLUMN entity_schema TO record_schema;
ALTER TABLE conversations RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_approvals RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_blueprint_migrations RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_channel_publications RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_comments RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_extension_annotation_revisions RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_reusable_attribute_attachments RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_status_transitions RENAME COLUMN entity_id TO record_id;
ALTER TABLE entity_unique_key_values RENAME COLUMN entity_id TO record_id;
ALTER TABLE extension_operation_run_entities RENAME COLUMN entity_id TO record_id;
ALTER TABLE file_retention_holds RENAME COLUMN entity_id TO record_id;
ALTER TABLE publication_channels RENAME COLUMN require_valid_entity TO require_valid_record;
ALTER TABLE rule_findings RENAME COLUMN entity_id TO record_id;
ALTER TABLE rule_runs RENAME COLUMN scope_entity_id TO scope_record_id;
ALTER TABLE solution_pack_plans RENAME COLUMN sample_entity_count TO sample_record_count;
ALTER TABLE workflow_run_action_targets RENAME COLUMN entity_id TO record_id;

-- Tables.
ALTER TABLE entities RENAME TO records;
ALTER TABLE entity_approvals RENAME TO record_approvals;
ALTER TABLE entity_blueprint_migrations RENAME TO record_blueprint_migrations;
ALTER TABLE entity_channel_publications RENAME TO record_channel_publications;
ALTER TABLE entity_comments RENAME TO record_comments;
ALTER TABLE entity_extension_annotation_revisions RENAME TO record_extension_annotation_revisions;
ALTER TABLE entity_reusable_attribute_attachments RENAME TO record_reusable_attribute_attachments;
ALTER TABLE entity_status_transitions RENAME TO record_status_transitions;
ALTER TABLE entity_unique_key_values RENAME TO record_unique_key_values;
ALTER TABLE extension_operation_run_entities RENAME TO extension_operation_run_records;
ALTER TABLE solution_pack_plan_sample_entities RENAME TO solution_pack_plan_sample_records;
