format_version = 1
code = "color"
name = "Color"
kind = "entity"

[display.dropdown_option]
fields = ["name", "hex"]

[views.detail]
type = "stack"

[[views.detail.children]]
type = "heading"
text = "Color"

[[views.detail.children]]
type = "field"
field = "name"

[[views.detail.children]]
type = "field"
field = "hex"

[views.edit]
type = "stack"

[[views.edit.children]]
type = "field"
field = "name"

[[views.edit.children]]
type = "field"
field = "hex"

[views.table]
type = "table"
fields = ["name", "hex"]

[[attributes]]
code = "name"
value_type = "string"

[[attributes]]
code = "hex"
value_type = "string"
