/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities/$entityId'
import { Route as EntitiesNewRouteImport } from './routes/entities/new'
import { Route as EntitiesEntityIdIndexRouteImport } from './routes/entities/$entityId/index'
import { Route as EntitiesEntityIdEditRouteImport } from './routes/entities/$entityId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesNewRoute = EntitiesNewRouteImport.update({
  id: '/entities/new',
  path: '/entities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdIndexRoute = EntitiesEntityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesEntityIdRoute,
} as any)
const EntitiesEntityIdEditRoute = EntitiesEntityIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EntitiesEntityIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities/$entityId': typeof EntitiesEntityIdRouteWithChildren
  '/entities/new': typeof EntitiesNewRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId/': typeof EntitiesEntityIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities/new': typeof EntitiesNewRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId': typeof EntitiesEntityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities/$entityId': typeof EntitiesEntityIdRouteWithChildren
  '/entities/new': typeof EntitiesNewRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId/': typeof EntitiesEntityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entities/$entityId'
    | '/entities/new'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entities/new' | '/entities/$entityId/edit' | '/entities/$entityId'
  id:
    | '__root__'
    | '/'
    | '/entities/$entityId'
    | '/entities/new'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRouteWithChildren
  EntitiesNewRoute: typeof EntitiesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/new': {
      id: '/entities/new'
      path: '/entities/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof EntitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId/': {
      id: '/entities/$entityId/'
      path: '/'
      fullPath: '/entities/$entityId/'
      preLoaderRoute: typeof EntitiesEntityIdIndexRouteImport
      parentRoute: typeof EntitiesEntityIdRoute
    }
    '/entities/$entityId/edit': {
      id: '/entities/$entityId/edit'
      path: '/edit'
      fullPath: '/entities/$entityId/edit'
      preLoaderRoute: typeof EntitiesEntityIdEditRouteImport
      parentRoute: typeof EntitiesEntityIdRoute
    }
  }
}

interface EntitiesEntityIdRouteChildren {
  EntitiesEntityIdEditRoute: typeof EntitiesEntityIdEditRoute
  EntitiesEntityIdIndexRoute: typeof EntitiesEntityIdIndexRoute
}

const EntitiesEntityIdRouteChildren: EntitiesEntityIdRouteChildren = {
  EntitiesEntityIdEditRoute: EntitiesEntityIdEditRoute,
  EntitiesEntityIdIndexRoute: EntitiesEntityIdIndexRoute,
}

const EntitiesEntityIdRouteWithChildren =
  EntitiesEntityIdRoute._addFileChildren(EntitiesEntityIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRouteWithChildren,
  EntitiesNewRoute: EntitiesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
