/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints/index'
import { Route as BlueprintsBlueprintIdRouteImport } from './routes/blueprints/$blueprintId'
import { Route as ContextsIndexRouteImport } from './routes/contexts/index'
import { Route as ContextsNewRouteImport } from './routes/contexts/new'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities/$entityId'
import { Route as EntitiesNewRouteImport } from './routes/entities/new'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginIdentifierRouteImport } from './routes/login/$identifier'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset/index'
import { Route as PasswordResetConfirmRouteImport } from './routes/password-reset/confirm'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceInvitationsRouteImport } from './routes/workspace/invitations'
import { Route as WorkspaceMembersRouteImport } from './routes/workspace/members'
import { Route as WorkspaceRolesRouteImport } from './routes/workspace/roles'
import { Route as EntitiesEntityIdIndexRouteImport } from './routes/entities/$entityId/index'
import { Route as EntitiesEntityIdEditRouteImport } from './routes/entities/$entityId/edit'
import { Route as EntitiesEntityIdMigrateRouteImport } from './routes/entities/$entityId/migrate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdRoute = BlueprintsBlueprintIdRouteImport.update({
  id: '/blueprints/$blueprintId',
  path: '/blueprints/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIndexRoute = ContextsIndexRouteImport.update({
  id: '/contexts/',
  path: '/contexts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsNewRoute = ContextsNewRouteImport.update({
  id: '/contexts/new',
  path: '/contexts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesNewRoute = EntitiesNewRouteImport.update({
  id: '/entities/new',
  path: '/entities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginIdentifierRoute = LoginIdentifierRouteImport.update({
  id: '/$identifier',
  path: '/$identifier',
  getParentRoute: () => LoginRoute,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetConfirmRoute = PasswordResetConfirmRouteImport.update({
  id: '/password-reset/confirm',
  path: '/password-reset/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceInvitationsRoute = WorkspaceInvitationsRouteImport.update({
  id: '/workspace/invitations',
  path: '/workspace/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceMembersRoute = WorkspaceMembersRouteImport.update({
  id: '/workspace/members',
  path: '/workspace/members',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRolesRoute = WorkspaceRolesRouteImport.update({
  id: '/workspace/roles',
  path: '/workspace/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdIndexRoute = EntitiesEntityIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesEntityIdRoute,
} as any)
const EntitiesEntityIdEditRoute = EntitiesEntityIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EntitiesEntityIdRoute,
} as any)
const EntitiesEntityIdMigrateRoute = EntitiesEntityIdMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => EntitiesEntityIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-health': typeof DataHealthRoute
  '/login': typeof LoginRouteWithChildren
  '/profile': typeof ProfileRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/entities/$entityId': typeof EntitiesEntityIdRouteWithChildren
  '/entities/new': typeof EntitiesNewRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/login/$identifier': typeof LoginIdentifierRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/workspace/invitations': typeof WorkspaceInvitationsRoute
  '/workspace/members': typeof WorkspaceMembersRoute
  '/workspace/roles': typeof WorkspaceRolesRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/contexts/': typeof ContextsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId/migrate': typeof EntitiesEntityIdMigrateRoute
  '/entities/$entityId/': typeof EntitiesEntityIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-health': typeof DataHealthRoute
  '/profile': typeof ProfileRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/entities/new': typeof EntitiesNewRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/login/$identifier': typeof LoginIdentifierRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/workspace/invitations': typeof WorkspaceInvitationsRoute
  '/workspace/members': typeof WorkspaceMembersRoute
  '/workspace/roles': typeof WorkspaceRolesRoute
  '/blueprints': typeof BlueprintsIndexRoute
  '/contexts': typeof ContextsIndexRoute
  '/login': typeof LoginIndexRoute
  '/password-reset': typeof PasswordResetIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId/migrate': typeof EntitiesEntityIdMigrateRoute
  '/entities/$entityId': typeof EntitiesEntityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-health': typeof DataHealthRoute
  '/login': typeof LoginRouteWithChildren
  '/profile': typeof ProfileRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/entities/$entityId': typeof EntitiesEntityIdRouteWithChildren
  '/entities/new': typeof EntitiesNewRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/login/$identifier': typeof LoginIdentifierRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/workspace/invitations': typeof WorkspaceInvitationsRoute
  '/workspace/members': typeof WorkspaceMembersRoute
  '/workspace/roles': typeof WorkspaceRolesRoute
  '/blueprints/': typeof BlueprintsIndexRoute
  '/contexts/': typeof ContextsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/entities/$entityId/edit': typeof EntitiesEntityIdEditRoute
  '/entities/$entityId/migrate': typeof EntitiesEntityIdMigrateRoute
  '/entities/$entityId/': typeof EntitiesEntityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-health'
    | '/login'
    | '/profile'
    | '/blueprints/$blueprintId'
    | '/contexts/new'
    | '/entities/$entityId'
    | '/entities/new'
    | '/invitations/accept'
    | '/login/$identifier'
    | '/password-reset/confirm'
    | '/workspace/invitations'
    | '/workspace/members'
    | '/workspace/roles'
    | '/blueprints/'
    | '/contexts/'
    | '/login/'
    | '/password-reset/'
    | '/workspace/'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/migrate'
    | '/entities/$entityId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-health'
    | '/profile'
    | '/blueprints/$blueprintId'
    | '/contexts/new'
    | '/entities/new'
    | '/invitations/accept'
    | '/login/$identifier'
    | '/password-reset/confirm'
    | '/workspace/invitations'
    | '/workspace/members'
    | '/workspace/roles'
    | '/blueprints'
    | '/contexts'
    | '/login'
    | '/password-reset'
    | '/workspace'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/migrate'
    | '/entities/$entityId'
  id:
    | '__root__'
    | '/'
    | '/data-health'
    | '/login'
    | '/profile'
    | '/blueprints/$blueprintId'
    | '/contexts/new'
    | '/entities/$entityId'
    | '/entities/new'
    | '/invitations/accept'
    | '/login/$identifier'
    | '/password-reset/confirm'
    | '/workspace/invitations'
    | '/workspace/members'
    | '/workspace/roles'
    | '/blueprints/'
    | '/contexts/'
    | '/login/'
    | '/password-reset/'
    | '/workspace/'
    | '/entities/$entityId/edit'
    | '/entities/$entityId/migrate'
    | '/entities/$entityId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataHealthRoute: typeof DataHealthRoute
  LoginRoute: typeof LoginRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  BlueprintsBlueprintIdRoute: typeof BlueprintsBlueprintIdRoute
  ContextsNewRoute: typeof ContextsNewRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRouteWithChildren
  EntitiesNewRoute: typeof EntitiesNewRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  PasswordResetConfirmRoute: typeof PasswordResetConfirmRoute
  WorkspaceInvitationsRoute: typeof WorkspaceInvitationsRoute
  WorkspaceMembersRoute: typeof WorkspaceMembersRoute
  WorkspaceRolesRoute: typeof WorkspaceRolesRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
  ContextsIndexRoute: typeof ContextsIndexRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId': {
      id: '/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof BlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/': {
      id: '/contexts/'
      path: '/contexts'
      fullPath: '/contexts/'
      preLoaderRoute: typeof ContextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/new': {
      id: '/contexts/new'
      path: '/contexts/new'
      fullPath: '/contexts/new'
      preLoaderRoute: typeof ContextsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/new': {
      id: '/entities/new'
      path: '/entities/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof EntitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/$identifier': {
      id: '/login/$identifier'
      path: '/$identifier'
      fullPath: '/login/$identifier'
      preLoaderRoute: typeof LoginIdentifierRouteImport
      parentRoute: typeof LoginRoute
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/confirm': {
      id: '/password-reset/confirm'
      path: '/password-reset/confirm'
      fullPath: '/password-reset/confirm'
      preLoaderRoute: typeof PasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/invitations': {
      id: '/workspace/invitations'
      path: '/workspace/invitations'
      fullPath: '/workspace/invitations'
      preLoaderRoute: typeof WorkspaceInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/members': {
      id: '/workspace/members'
      path: '/workspace/members'
      fullPath: '/workspace/members'
      preLoaderRoute: typeof WorkspaceMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/roles': {
      id: '/workspace/roles'
      path: '/workspace/roles'
      fullPath: '/workspace/roles'
      preLoaderRoute: typeof WorkspaceRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId/': {
      id: '/entities/$entityId/'
      path: '/'
      fullPath: '/entities/$entityId/'
      preLoaderRoute: typeof EntitiesEntityIdIndexRouteImport
      parentRoute: typeof EntitiesEntityIdRoute
    }
    '/entities/$entityId/edit': {
      id: '/entities/$entityId/edit'
      path: '/edit'
      fullPath: '/entities/$entityId/edit'
      preLoaderRoute: typeof EntitiesEntityIdEditRouteImport
      parentRoute: typeof EntitiesEntityIdRoute
    }
    '/entities/$entityId/migrate': {
      id: '/entities/$entityId/migrate'
      path: '/migrate'
      fullPath: '/entities/$entityId/migrate'
      preLoaderRoute: typeof EntitiesEntityIdMigrateRouteImport
      parentRoute: typeof EntitiesEntityIdRoute
    }
  }
}

interface LoginRouteChildren {
  LoginIdentifierRoute: typeof LoginIdentifierRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginIdentifierRoute: LoginIdentifierRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface EntitiesEntityIdRouteChildren {
  EntitiesEntityIdEditRoute: typeof EntitiesEntityIdEditRoute
  EntitiesEntityIdMigrateRoute: typeof EntitiesEntityIdMigrateRoute
  EntitiesEntityIdIndexRoute: typeof EntitiesEntityIdIndexRoute
}

const EntitiesEntityIdRouteChildren: EntitiesEntityIdRouteChildren = {
  EntitiesEntityIdEditRoute: EntitiesEntityIdEditRoute,
  EntitiesEntityIdMigrateRoute: EntitiesEntityIdMigrateRoute,
  EntitiesEntityIdIndexRoute: EntitiesEntityIdIndexRoute,
}

const EntitiesEntityIdRouteWithChildren =
  EntitiesEntityIdRoute._addFileChildren(EntitiesEntityIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataHealthRoute: DataHealthRoute,
  LoginRoute: LoginRouteWithChildren,
  ProfileRoute: ProfileRoute,
  BlueprintsBlueprintIdRoute: BlueprintsBlueprintIdRoute,
  ContextsNewRoute: ContextsNewRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRouteWithChildren,
  EntitiesNewRoute: EntitiesNewRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  PasswordResetConfirmRoute: PasswordResetConfirmRoute,
  WorkspaceInvitationsRoute: WorkspaceInvitationsRoute,
  WorkspaceMembersRoute: WorkspaceMembersRoute,
  WorkspaceRolesRoute: WorkspaceRolesRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
  ContextsIndexRoute: ContextsIndexRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
