[package]
name = "catalog-extension-manifest"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
catalog-validation = { path = "../validation" }
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
zstd.workspace = true
