[package]
name = "api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
catalog-domain = { path = "../../crates/domain" }
catalog-events = { path = "../../crates/events" }
catalog-extension-manifest = { path = "../../crates/extension-manifest" }
catalog-extension-runtime = { path = "../../crates/extension-runtime" }
catalog-http = { path = "../../crates/http" }
catalog-repository = { path = "../../crates/repository" }
catalog-storage = { path = "../../crates/storage" }
catalog-workers = { path = "../../crates/workers" }
dotenvy.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
image.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "rustls-tls"] }
rust_decimal.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tar.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true
zstd.workspace = true
